# use an existing docker image as a base


FROM alpine

# Download and isntall a dependency

RUN apk add --update redis
RUN apk add --update gcc

# Tell the image what to do when it starts

CMD ["redis-server"]
#as a container